version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/java17"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "feat"
      include: "scope"
    ignore:
      - dependency-name: "eclipse-temurin"
        update-types:
          - "version-update:semver-major"
  - package-ecosystem: "docker"
    directory: "/java21"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "feat"
      include: "scope"
    ignore:
      - dependency-name: "eclipse-temurin"
        update-types:
          - "version-update:semver-major"
  - package-ecosystem: "docker"
    directory: "/java25"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "feat"
      include: "scope"
    ignore:
      - dependency-name: "eclipse-temurin"
        update-types:
          - "version-update:semver-major"
  - package-ecosystem: "docker"
    directory: "/latest"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "feat"
      include: "scope"